baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Personal Website'
theme = 'LoveIt'

[params.header.title]
    logo = ""
    name = "Corentin LEGER"

[params.home]
  [params.home.profile]
    title = "AI Research Engineer"
    subtitle = "Welcome to my website ! "
  
[params.social]
    github = "corentinlger"
    linkedin = "corentin-l"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1

  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 2

  [[menu.main]]
    name = "Education"
    url = "/education"
    weight = 3

  [[menu.main]]
    name = "Experiences"
    url = "/experiences"
    weight = 4

  [[menu.main]]
    name = "Projects"
    url = "/posts"
    weight = 5

[params.page]
  [params.page.share]
      HackerNews = false
      enable = false
      Twitter = false
      Facebook = false
      Line = false
      Weibo = false




