baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Corentin LEGER'
theme = 'LoveIt'

[params]
  defaultTheme = "light"

[params.header.title]
    logo = ""
    name = "Corentin LEGER"

[params.home]
  [params.home.profile]
    title = "Research Engineer in the Flowers team @Inria"
    subtitle = "Hi, welcome on my website (:"
  
[params.social]
    github = "corentinlger"
    linkedin = "corentin-l"
    Twitter = "corentinlger"


[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/posts/"
    weight = 2

[params.page]
  [params.page.share]
      HackerNews = false
      enable = false
      Twitter = false
      Facebook = false
      Line = false
      Weibo = false




