baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Corentin LEGER'
theme = 'LoveIt'

[params]
  defaultTheme = "dark"

[params.header.title]
    logo = ""
    name = "Corentin LEGER"

[params.home]
  [params.home.profile]
    title = "AI Research Engineer @ Inria"
    subtitle = "Hi, welcome to my website!"
    avatarURL = "/images/toff.png"
    bio = "Hi I'm Corentin, a Research Engineer in the Flowers team. My interests include Machine Learning, Reinforcement Learning, Evolutionary Strategies, and LLMs. I'm currently seeking an engineering position in one of these areas."
    
[params.social]
    github = "corentinlger"
    Googlescholar = "user=V-qyPxkAAAAJ&hl=en"
    Twitter = "corentinlger"
    linkedin = "corentin-l"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
  [[menu.main]]
    name = "Projects"
    url = "/posts/"
    weight = 4

[params.page]
  [params.page.share]
      HackerNews = false
      enable = false
      Twitter = false
      Facebook = false
      Line = false
      Weibo = false




