baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Corentin LEGER'
theme = 'LoveIt'

[params]
  defaultTheme = "dark"

[params.header.title]
    logo = ""
    name = "Corentin LEGER"

[params.home]
  [params.home.profile]
    title = "AI Research Engineer @ Inria"
    subtitle = "Hi, welcome to my website!"
    avatarURL = "/images/toff.png"
    bio = "Hi I'm Corentin, a research engineer in the Flowers team. I'm particularly interested in ML, Reinforcement Learning, Evolutionary Strategies and LLMs. I am currently looking for a position related to one of these fields."
    
[params.social]
    github = "corentinlger"
    Googlescholar = "user=V-qyPxkAAAAJ&hl=en"
    Twitter = "corentinlger"
    linkedin = "corentin-l"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/posts/"
    weight = 2

[params.page]
  [params.page.share]
      HackerNews = false
      enable = false
      Twitter = false
      Facebook = false
      Line = false
      Weibo = false




